# Generated by Django 5.2 on 2025-05-16 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0004_todo_create"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo",
            old_name="create",
            new_name="completed",
        ),
    ]
